### ISSUE TITLE
does this still work / does it need adaptation?

### ISSUE THREAD

**Issue by mrambossek** [SapuSeven/Digitales-Amt-Integrity-Bypass#1]
Hi,

i just tried using it but the Digitales Amt app still complains about root.
did they change some stuff that requires adaptation of this module, maybe?

thanks & regards

**Comment by andyboeh** [comment]
working properly for me, I signed several documents today - did you uncheck "Enforce DenyList" in Magisk? I had it checked at the first try and it would still complain. And did you configure the LSPosed module?

**Comment by mrambossek** [comment]
yeah, that was exactly the problem; i did, and still do, have "enforce denylist" on for other apps,
but i initially added the Digitales Amt app to the denylist. even though i used the "recommended" menu option to "select" the greyed out (because-on-denylist) DA app, it seems to ignore it...

now that i removed it from the magisk denylist, and re-selected it in the LSPosed module, it works =)
thanks!

**Comment by SapuSeven** [comment]
Glad it works.
The Digitales Amt app needs to be removed from the Magisk denylist in order for LSPosed to be able to make changes.

**Comment by mrambossek** [comment]
maybe put that into the readme, that would help a lot =)

huge thanks for creating this!

**Comment by andyboeh** [comment]
Thanks from my side as well - I was about to create such a module myself when I discovered yours by chance.
It took me some experimentation with deny list as well to find that out. In the meantime, I don't need to enforce the deny list at all - Shamiko does the rest.

**Comment by SapuSeven** [comment]
FYI - I updated the README with your suggestions.
