### ISSUE TITLE
App version 2.4.0 crashes

### ISSUE THREAD

**Issue by andyboeh** [SapuSeven/Digitales-Amt-Integrity-Bypass#2]
This is actually not an issue, more of a warning: I just updated to the latest version of Digitales Amt (2022/11/09) and - it doesn't start anymore. It doesn't even display an error message, it just crashes. I doubt it has something to do with the integrity bypass, in logcat I see an IllegalArgumentException that apps targeting S+ requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

**Comment by mrambossek** [comment]
What version is that? I am apparently on the same version date wise - SwiftBackup says 2.3.0 - and it seems to launch fine?

**Comment by andyboeh** [comment]
2.4.0 - It works after deleting all data. Thank you, Digitales Amt. And it detects root again...

**Comment by andyboeh** [comment]
I have to correct myself: it detected root because LSPosed didn't pick it up. After a reboot, it crashes again. Disabling the integrity bypass module didn't help. Deleting data didn't help. Uninstalling (disabled LSPosed module), reboot, reinstall from PlayStore didn't help. So I can't even get it to start again.
I'll see if I can get a 2.3.0 APK somewhere...

**Comment by mrambossek** [comment]
https://drive.google.com/file/d/1_GsjMTgpgBO7AuifKg6YRbmc2FKhGINY/view?usp=drivesdk

Hope i exported the apk correctly...

**Comment by andyboeh** [comment]
Thanks, you did - I'm back on 2.3.0 and everything is working properly again. I'd be interested in other experiences with 2.4.0 :)

**Comment by SapuSeven** [comment]
I just updated the app from Google play - looks like 2.4.1 is the current version. I think they had a bug in 2.4.0 and fixed it quickly. This version works flawlessly for me.

**Comment by andyboeh** [comment]
@SapuSeven Thanks, you're right: 2.4.1 is out and is working properly. Two lessons learned:

1. Don't update right away
2. There seem to be no QA for Digitales Amt, so -> don't update right away.

**Comment by mrambossek** [comment]
I *think* now is the time, though?

I just got the "rooted" error on my new phone, so i am not 100% sure. All the other things requiring SN etc work though, after some trial and error with magisk on the S23U :) so im fairly sure its universal, but please someone else verify ...

App Version 2.5.2

**Comment by SapuSeven** [comment]
I can't confirm this.
V2.5.2 works great for me.

Please open a new issue of you have problems with a version other than 2.4.0.
