### ISSUE TITLE
Anyone got the eAusweise app to work?

### ISSUE THREAD

**Issue by raldone01** [SapuSeven/Digitales-Amt-Integrity-Bypass#3]

**Comment by mrambossek** [comment]
i just tested it and it seems to work just fine for me
as i do not actually posess a drivers license, i can't fully test (or make much use of) it; but it would let me "login via Digitales Amt" and seems to work fine so far...

**Comment by raldone01** [comment]
Thank you, very interesting. I am stuck after the Digitales Amt apps sends me back. If I have some time I will look at the logcat.

**Comment by SapuSeven** [comment]
I can confirm the app works for me without even adding it to the zygisk deny list. Are you passing the safetynet check?

**Comment by raldone01** [comment]
No I am not passing safetynet. Probably the issue. Weird that digitales amt works fine without it.
