### ISSUE TITLE
(me-only?) problem with DA 2.5.2

### ISSUE THREAD

**Issue by mrambossek** [SapuSeven/Digitales-Amt-Integrity-Bypass#4]
- Galaxy S23U (AP_S918BXXU1AWA6_S918BXXU1AWA6_MQB61070574_REV00_user_low_ship_MULTI_CERT_meta_OS13)
- magisk 25.2, LSPosed 1.8.6 (6712)
- DA and DA-IB are NOT on the exclude list
- module is enabled and DA selected as single (recommended) entry
- only other LSP mod is KnoxPatch

moved a bunch of apps with swiftbackup from my old phone, including DA; but tried wiping storage now, still getting "rooted" message

other SN-sensitive apps work fine so far (banking, games)

any hints/steps/guides on how i could debug this? thanks :)

**Comment by mrambossek** [comment]
Nevermind.. I fiddled around, uninstalling and reinstalling things and suddenly it works again.. I'm guessing the lsposed hooks somehow didn't "apply".

Thanks :)

**Comment by SapuSeven** [comment]
Good, glad you got it to work :)
