### ISSUE TITLE
Not required on 3.0.6 anymore despite open bootloader?

### ISSUE THREAD

**Issue by andyboeh** [SapuSeven/Digitales-Amt-Integrity-Bypass#5]
I upgraded to 3.0.6. I do get a warning regarding an open bootloader, but this module is not required any more - seems like Digitales Amt now allows the usage of the app even with an open bootloader. Is this also your experience?

However, it would be nice to be able to hide the warning message.

**Comment by SapuSeven** [comment]
I have an open bootloader as well, but I don't get that message (app version 3.0.6).
For me the module still works as expected.

I believe that the module should still be able to hide the error message.

**Comment by andyboeh** [comment]
Hm...seems like I had a problem with my LSPosed configuration. You are right, it **is** able to hide the open bootloader. 

However, apart from an annoying message, Digitales Amt now works even with open boot loaders (it still doesn't like root, but hiding root via Magisk seems to be sufficient).
